#!/bin/sh

set -e

progname="${0##*/} test cases"

case $SCRIPT_LIB_ROOT in
"")
	_libroot=/usr/share/scriptlib
	;;
*)
	_libroot=$SCRIPT_LIB_ROOT
	;;
esac

echo "using \$_libroot: '$_libroot'"

. ${_libroot}/file/check
tests=0 # running total performed
errors=0

#
# check_dir_exist()
#
test=check_dir_exist

# true
for t in \
	/ \
	/etc \
	$PWD
do
	tests=$(( tests + 1 ))
	if ! $test -q "$t"; then
		echo "FAILED: $test '$t'"
		errors=$(( errors + 1 ))
	fi
done

# false
for t in \
	1.1.1 \
	1.1.1.1/24 \
	::1 \
	fe80::1 \
	123.456.789.123 \
	test \
	256.256.256.256
do
	tests=$(( tests + 1 ))
	if $test -q "$t"; then
		echo "FAILED: $test '$t'"
		errors=$(( errors + 1 ))
	fi
done
# false/whitespace (redir stderr b/c $test will complain
for t in \
	'' \
	\"\" \
	'	'
do
	tests=$(( tests + 1 ))
	if $test "$t" >/dev/null 2>&1; then
		echo "$FAILED: $test: '$t'"
		errors=$(( errors +1 ))
	fi
done

if [ "$errors" -ne 0 ]; then
        echo "$progname $errors/$tests tests FAILED"
	exit 1
fi
echo "$tests passed"

